In [1]:
from neural import *
nn = ConvolutionNetwork([1,1])
print(nn.stages[0].units[0][0].coeff_len)
coeff = np.ones(nn.coeff_len)
coeff[0:10] = 0 # offsets
coeff[10:20] = -1 # self
#coeff = np.vectorize(abs)(10*np.random.normal(size=nn.coeff_len)).astype(int)
inp = np.zeros(nn.input_len)
inp[26] = 1
#mask = np.ones(49)
#mask[0:21] = 0
#inp = inp*mask
nn.set_coeff(coeff)
square_print(inp)
square_print('******')
square_print(nn(inp))

53
[ 0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  1.  0.]
[ 0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.]
******






[ 0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  1.  0.  1.]
[ 0.  0.  0.  1.  0.  0.  0.]
[ 0.  0.  0.  0.  0. -1.  0.]
[ 0.  0.  0.  1.  0.  0.  0.]
[ 0.  0.  0.  0.  1.  0.  1.]
[ 0.  0.  0.  0.  0.  0.  0.]


In [2]:
a = generate_all_moves_by_index()[8]
tmp = np.zeros(49)
tmp[a] = 1
tmp[8] = -1
square_print(tmp)

[ 0.  0.  0.  1.  0.  0.  0.]
[ 0. -1.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  1.  0.  0.  0.]
[ 1.  0.  1.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.]


In [3]:
joint_ind, n = move_convolution_indices()
print(joint_ind[3],generate_all_moves_by_index()[3])

[(-1, 6), (3, 16), (8, 40), (16, 41), (18, 41), (12, 40)] [18, 12, 8, 16]
